#!/bin/bash

#if number of args is less then 1 use path in spec
if [ $# -eq 0 ]; then
       path=/iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_1/scanner3DTop/recent_changes/2020-03-02/plantcrop/combined_pointclouds
fi

if [ $# -eq 1 ]; then
       path=$1
fi       


touch combined_pointcloud_path
set -u
#move to smaller dataset, should fix the hard code
icd /iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_1/scanner3DTop/recent_changes/2020-03-02/plantcrop/combined_pointclouds
#get names of plants
ils >> combined_pointcloud_path

#this could be better
tail -n +2 "combined_pointcloud_path" >> combined_pointcloud_path_re
tail -n +2 "combined_pointcloud_path_re" >> combined_pointcloud_path_re2
python clean_path.py

rm combined_pointcloud_path
rm combined_pointcloud_path_re


#below this line is just testing 

#touch recus_pointcloud_path

#ils -r >> recus_pointcloud_path


